version: '3'
services:
  users-service:
    container_name: users-service
    build: .
    volumes:
      - .:/var/www
      - ./config/php-dev.ini:/usr/local/etc/php/php.ini
    ports:
      - "8080:80"
    # depends_on:
    #   - users-db
    environment:
      APP_ENV: development
      MYSQL_HOST: users-db
      MYSQL_USER: users
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: users
    # external_links:
      # - redis-session
      # - users-db
    network_mode: bridge

  # users-db:
  #   container_name: users-db
  #   image: mysql:5.7
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: passwordroot
  #     MYSQL_USER: users
  #     MYSQL_PASSWORD: password123
  #     MYSQL_DATABASE: users
  #   network_mode: bridge
